In [2]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr.shape()

NameError: name 'arr' is not defined

In [7]:
arr1.shape

(5,)

In [9]:
arr1.dtype

dtype('int64')

In [11]:
arr1.ndim

1

In [13]:
arr1.size

5

##2D Array

In [15]:
arr2 = np.array([[1,4,5],[3,4,5]])

In [16]:
arr2

array([[1, 4, 5],
       [3, 4, 5]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 3)

### 3D Array

In [19]:
arr3 = np.array([[[1,4,5],[3,4,5]], [[1,4,5],[3,4,5]], [[1,4,5],[3,4,5]]])
arr3

array([[[1, 4, 5],
        [3, 4, 5]],

       [[1, 4, 5],
        [3, 4, 5]],

       [[1, 4, 5],
        [3, 4, 5]]])

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(3, 2, 3)

In [22]:
arr3.size

18

## Create Random Array

In [23]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.75989832, 0.29777209, 0.39212034],
        [0.96745935, 0.71635342, 0.7510647 ]],

       [[0.02923388, 0.25858688, 0.36845552],
        [0.58584762, 0.75637736, 0.96494326]],

       [[0.70548137, 0.95187442, 0.83140336],
        [0.45215023, 0.19651388, 0.43065749]]])

In [24]:
randomArr.dtype

dtype('float64')

In [25]:
zeros = np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
zeros.ndim

3

In [27]:
full = np.full((3,2,3), 9)

In [28]:
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [29]:
ones = np.ones((3,2,3))

In [30]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
np.add(full, randomArr)

array([[[9.75989832, 9.29777209, 9.39212034],
        [9.96745935, 9.71635342, 9.7510647 ]],

       [[9.02923388, 9.25858688, 9.36845552],
        [9.58584762, 9.75637736, 9.96494326]],

       [[9.70548137, 9.95187442, 9.83140336],
        [9.45215023, 9.19651388, 9.43065749]]])

In [32]:
np.divide(a1,a2)
np.multply(a1,a2)
np.sqrt(25)
np.abs(-2)
np.power(2,8)
np.log(24)
np.max(a1)
np.min(a1)

NameError: name 'a1' is not defined

In [33]:
arr3

array([[[1, 4, 5],
        [3, 4, 5]],

       [[1, 4, 5],
        [3, 4, 5]],

       [[1, 4, 5],
        [3, 4, 5]]])

In [35]:
arr3[0,0,2] = 500

In [36]:
arr3

array([[[  1,   4, 500],
        [  3,   4,   5]],

       [[  1,   4,   5],
        [  3,   4,   5]],

       [[  1,   4,   5],
        [  3,   4,   5]]])

In [37]:
arr3.sort

<function ndarray.sort>

In [38]:
arr3

array([[[  1,   4, 500],
        [  3,   4,   5]],

       [[  1,   4,   5],
        [  3,   4,   5]],

       [[  1,   4,   5],
        [  3,   4,   5]]])

In [39]:
arr3.shape

(3, 2, 3)

In [40]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  3,   4,   5],
        [  1,   4,   5]],

       [[  3,   4,   5],
        [  1,   4,   5],
        [  3,   4,   5]]])

In [41]:
arr3_reshape

array([[[  1,   4, 500],
        [  3,   4,   5],
        [  1,   4,   5]],

       [[  3,   4,   5],
        [  1,   4,   5],
        [  3,   4,   5]]])

## Apending & inserting

In [43]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
new_array = np.ones((3,2,3))

In [45]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [48]:
appd = np.append(zeros, new_array, axis=0)

In [49]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

## Delete

In [3]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.24764373, 0.48737157, 0.92881584],
        [0.20424281, 0.45905305, 0.84426952]],

       [[0.68852019, 0.06070415, 0.35234578],
        [0.65659721, 0.39250979, 0.93921221]],

       [[0.30842954, 0.28967657, 0.85028741],
        [0.33175466, 0.34376362, 0.42409817]]])

In [5]:
arr5 = np.delete(arr4, 0, axis=1)

In [6]:
arr5

array([[[0.20424281, 0.45905305, 0.84426952]],

       [[0.65659721, 0.39250979, 0.93921221]],

       [[0.33175466, 0.34376362, 0.42409817]]])

In [7]:
np.save("new_array", arr5)

In [8]:
np.load("new_array.npy")

array([[[0.20424281, 0.45905305, 0.84426952]],

       [[0.65659721, 0.39250979, 0.93921221]],

       [[0.33175466, 0.34376362, 0.42409817]]])